apiVersion: v1
kind: Pod
metadata:
  name: gvirtus-tests
  labels:
    gvirtus.io/enabled: "true"  # Enable GVirtuS for this pod
spec:
  restartPolicy: Never
  containers:
  - name: gvirtus-tests-container
    image: taslanidis/gvirtus-tests:latest
    imagePullPolicy: Always
    command: ["sleep infinity"]  # Change this based on your app path and executable
  # nodeName: daisthree # Uncomment for testing
  # resources:
  #   limits:
  #     nvidia.com/gpu: 1  # Request 1 GPU for the container
