apiVersion: v1
kind: ServiceAccount
metadata:
  name: gvirtus-webhook
  namespace: gvirtus-system
  labels:
    app.kubernetes.io/name: gvirtus-webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: gvirtus
    app.kubernetes.io/version: "0.1.0-alpha"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gvirtus-webhook
  labels:
    app.kubernetes.io/name: gvirtus-webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: gvirtus
    app.kubernetes.io/version: "0.1.0-alpha"
rules:
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gvirtus-webhook
  labels:
    app.kubernetes.io/name: gvirtus-webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: gvirtus
    app.kubernetes.io/version: "0.1.0-alpha"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gvirtus-webhook
subjects:
- kind: ServiceAccount
  name: gvirtus-webhook
  namespace: gvirtus-system
