apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: gvirtus-mutating-webhook-configuration
  labels:
    app.kubernetes.io/name: gvirtus-mutating-webhook-configuration
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of: gvirtus
    app.kubernetes.io/version: "0.1.0"
webhooks:
  - name: gvirtus-webhook.gvirtus-system.svc.cluster.local
    clientConfig:
      service:
        name: gvirtus-webhook
        namespace: gvirtus-system
        path: /mutate
        port: 443
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "*"
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail
    objectSelector:
      matchLabels:
        gvirtus.io/enabled: "true"
    # alternatively, you can use matchExpressions to match on multiple labels
    #    matchExpressions:
    #    - key: "gvirtus.io/enabled"
    #      operator: "In"
    #      values:
    #      - "true"
