apiVersion: v1
kind: Service
metadata:
  name: gvirtus-backend
  namespace: gvirtus-system
  labels:
    app.kubernetes.io/name: gvirtus-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: gvirtus
    app.kubernetes.io/version: "0.1.0-alpha"
spec:
  selector:
    app.kubernetes.io/name: gvirtus-backend
  ports:
    - protocol: TCP
      port: 34567
      targetPort: 9999
  type: ClusterIP
