apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gvirtus-backend
  namespace: gvirtus-system
  labels:
    app.kubernetes.io/name: gvirtus-backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: gvirtus
    app.kubernetes.io/version: "0.1.0-alpha"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gvirtus-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gvirtus-backend
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: gvirtus
        app.kubernetes.io/version: "0.1.0-alpha"
    spec:
      nodeSelector:
        gvirtus.io/backend.allowed: "true"
        nvidia.com/gpu.present: "true"
      containers:
        - name: gvirtus-backend
          image: taslanidis/gvirtus-dependencies:cuda12.6.3-cudnn-ubuntu22.04
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
          volumeMounts:
            - name: cmake-volume
              mountPath: /gvirtus/cmake/
            - name: etc-volume
              mountPath: /gvirtus/etc
            - name: include-volume
              mountPath: /gvirtus/include/
            - name: plugins-volume
              mountPath: /gvirtus/plugins/
            - name: src-volume
              mountPath: /gvirtus/src
            - name: tools-volume
              mountPath: /gvirtus/tools/
            - name: cmakelists-volume
              mountPath: /gvirtus/CMakeLists.txt
              subPath: CMakeLists.txt
      volumes:
        - name: cmake-volume
          hostPath:
            path: /home/taslanidis/git/GVirtuS/cmake
            type: Directory
        - name: etc-volume
          hostPath:
            path: /home/taslanidis/git/GVirtuS/etc
            type: Directory
        - name: include-volume
          hostPath:
            path: /home/taslanidis/git/GVirtuS/include
            type: Directory
        - name: plugins-volume
          hostPath:
            path: /home/taslanidis/git/GVirtuS/plugins
            type: Directory
        - name: src-volume
          hostPath:
            path: /home/taslanidis/git/GVirtuS/src
            type: Directory
        - name: tools-volume
          hostPath:
            path: /home/taslanidis/git/GVirtuS/tools
            type: Directory
        - name: cmakelists-volume
          hostPath:
            path: /home/taslanidis/git/GVirtuS
            type: Directory
      restartPolicy: Always