apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gvirtus-labeler
  namespace: gvirtus-system
  labels:
    app.kubernetes.io/name: gvirtus-labeler
    app.kubernetes.io/component: labeler
    app.kubernetes.io/part-of: gvirtus
    app.kubernetes.io/version: "0.1.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gvirtus-labeler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gvirtus-labeler
        app.kubernetes.io/component: labeler
        app.kubernetes.io/part-of: gvirtus
        app.kubernetes.io/version: "0.1.0"
    spec:
      serviceAccountName: gvirtus-labeler
      containers:
        - name: labeler
          image: taslanidis/gvirtus-labeler:latest
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      restartPolicy: Always
