apiVersion: v1
kind: Namespace
metadata:
  name: gvirtus-detector

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gvirtus-detector-sa
  namespace: gvirtus-detector

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gvirtus-detector-label-patch
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "patch", "update", "label"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gvirtus-detector-label-binding
subjects:
  - kind: ServiceAccount
    name: gvirtus-detector-sa
    namespace: gvirtus-detector
roleRef:
  kind: ClusterRole
  name: gvirtus-detector-label-patch
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gvirtus-detector
  namespace: gvirtus-detector
spec:
  selector:
    matchLabels:
      app: gvirtus-detector
  template:
    metadata:
      labels:
        app: gvirtus-detector
    spec:
      serviceAccountName: gvirtus-detector-sa
      hostPID: true
      containers:
        - name: gvirtus-detector
          image: taslanidis/gvirtus-node-setup:latest
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
