apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gvirtus-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: gvirtus-device-plugin
  template:
    metadata:
      labels:
        app: gvirtus-device-plugin
    spec:
      nodeSelector:
        gvirtus-role: frontend
      initContainers:
      - name: bootstrap-host
        image: busybox:latest
        securityContext:
          privileged: true
        command:
        - /bin/sh
        - -c
        - |
          set -eux
          # 1) Create CDI directory and write the spec
          mkdir -p /host/etc/cdi
          cat << 'EOF' > /host/etc/cdi/gvirtus-device.yaml
          cdiVersion: 0.6.0
          kind: nvidia.com/gpu
          devices:
          - name: device_0
            containerEdits:
              deviceNodes:
              - hostPath: /dev/gvirtus/device_0
                path: /dev/gvirtus/device_0
                type: c
                permissions: rw
              mounts:
              - hostPath: /usr/local/gvirtus/lib/device_0.so
                containerPath: /usr/local/gvirtus/lib/device_0.so
                options: ["ro", "nosuid", "nodev", "bind"]
          EOF

          # 2) Create the gvirtus character device
          mkdir -p /host/dev/gvirtus
          rm -f /dev/gvirtus/device_0
          mknod /dev/gvirtus/device_0 c 89 1
          chmod 666 /host/dev/gvirtus/device_0

          # 3) Create the gvirtus device .so
          mkdir -p /host/usr/local/gvirtus/lib
          touch /host/usr/local/gvirtus/lib/device_0.so
          chmod 644 /host/usr/local/gvirtus/lib/device_0.so
        volumeMounts:
        - name: host-root
          mountPath: /host
      containers:
      - name: plugin
        image: taslanidis/gvirtus-device-plugin:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: kubelet
          mountPath: /var/lib/kubelet
      volumes:
      - name: host-root
        hostPath:
          path: /
      - name: kubelet
        hostPath:
          path: /var/lib/kubelet
