apiVersion: v1
kind: Pod
metadata:
  name: cuda-app-pod
  labels:
    gvirtus.io/enabled: "true"  # Enable GVirtuS for this pod
spec:
  restartPolicy: Never
  containers:
  - name: cuda-app-container
    image: taslanidis/gvirtus-app-example
    imagePullPolicy: IfNotPresent
    command: ["./cudart_example"]  # Change this based on your app path and executable
  # nodeName: daisthree
  resources:
    limits:
      nvidia.com/gpu: 1  # Request 1 GPU for the container
